# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7715c5b0e0c575ed2b3344f9882306f45d8bae5ce8a35befe09db3275e546323712f95308409471a361dc521e0b6ef33085d534b3142001a3d5b703c6d99d1e

test:
  secret_key_base: 2adbcd3d646fff27dc0758d702e1f13ef57e3a5e5dffad88d98434c146a426412b8516033c4f4e55b2b164a2b03a12f145b6dff61132ac1f08dae75af635901a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
